---
os: linux
dist: focal
language: python
python:
  - 3.8
env:
  global:
    - VAGRANT_DEFAULT_PROVIDER: libvirt
    - PY_COLORS: 1
  jobs:
    - MOLECULE_DISTRO: generic/ubuntu2004
    - MOLECULE_DISTRO: generic/debian11
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
  pip: true
before_install:
  - |
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt update && sudo apt install vagrant
install:
  - |
    sudo apt-get install -y build-essential qemu-kvm qemu-utils libvirt-dev libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager dnsmasq
    CONFIGURE_ARGS="with-libvirt-include=/usr/share/libvirt with-libvirt-lib=/usr/lib64" sudo vagrant plugin install vagrant-libvirt
before_script:
  - |
    sudo -H pip install --upgrade --ignore-installed --requirement requirements.txt
    molecule --version
script:
  - |
    sudo -E molecule -vvv test
