---
- hosts: pgcluster
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Install dependencies
      apt: 
        name: 
          - python3-apt
          - vim
        update_cache: yes
    - name: Use python3 by default
      alternatives: 
        path: /usr/bin/python3
        link: /usr/bin/python
        name: python
        priority: 1
    - name: Debug variables
      debug:
        msg:
          "ansible_python_interpreter": "{{ ansible_python_interpreter }}"
          "ansible_python_version": "{{ ansible_python_version }}"
          "postgresql_version": "{{ postgresql_version }}"
          "repmgr_master": "{{ repmgr_master }}"
          "repmgr_target_group": "{{ repmgr_target_group }}"
          "repmgr_node_id": "{{ repmgr_node_id }}"
          "repmgr_failover": "{{ repmgr_failover }}"
  roles:
    - name: ../ansible-role-postgresql-ha
