---
- hosts: pgcluster
  gather_facts: yes
  become: yes
  debugger: on_failed

  vars_files:
    - ./vars.yml
    - ./vars/postgresql_11.yml
  vars:
    role_path: "{{ lookup('env', 'ROLE_PATH') }}"

  roles:
    - name: "{{ role_path if role_path is defined and role_path else lookup('env', 'HOME') + '/ansible-role-postgresql-ha' }}"
