---
- name: PostgreSQL | Extensions | Add 2nd Quadrant repo gpg key | apt
  apt_key:
    url: "{{ repmgr_gpg_key_url }}"
  when: ansible_pkg_mgr == "apt"

- name: PostgreSQL | Extensions | Add 2nd Quadrant repo for repmgr | apt
  apt_repository:
    repo: "{{ repmgr_apt_repository }}"
    filename: 2ndquadrant-dl-default-release
  when: ansible_pkg_mgr == "apt"

- name: PostgreSQL | Extensions | Make sure the postgres repmgr extensions are installed | apt
  apt:
    name: "postgresql-{{ postgresql_version }}-repmgr"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_pkg_mgr == "apt"
  notify: restart postgresql
