---
- name: PostgreSQL | FDW | MySQL
  package:
    name: "{{ postgresql_fdw_mysql_packages }}"
    state: present
  when: postgresql_fdw_mysql

- name: PostgreSQL | FDW | OGR
  package:
    name: "{{ postgresql_fdw_ogr_packages }}"
    state: present
  when: postgresql_fdw_ogr
