---
- name: restart postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
    enabled: yes

- name: restart cluster
  shell: pg_ctlcluster {{postgresql_version}} {{postgresql_cluster_name}} restart