---
- name: restart postgresql
  shell: 
    cmd: pg_ctlcluster {{ postgresql_version }} {{ postgresql_cluster_name }} restart
    executable: /bin/bash
  become: yes
  become_user: "{{ postgresql_service_user }}"
