---
- name: Converge
  hosts: pgcluster
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: Debug variables
      debug:
        msg:
          "ansible_python_version": "{{ ansible_python_version }}"
          "ansible_version.full": "{{ ansible_version.full }}"
          "postgresql_version": "{{ postgresql_version }}"
          "repmgr_version": "{{ repmgr_version }}"
          "repmgr_master": "{{ repmgr_master }}"
          "repmgr_target_group": "{{ repmgr_target_group }}"
          "repmgr_node_id": "{{ repmgr_node_id }}"
  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
