---
- name: Prepare
  hosts: pgcluster
  gather_facts: no
  become: yes

  pre_tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:

    - name: Gather facts for the first time
      ansible.builtin.setup:

    - name: Install python dependencies
      ansible.builtin.apt: 
        name: 
          - python3-apt
        update_cache: yes

    - name: Use python3 by default
      community.general.system.alternatives: 
        path: /usr/bin/python3
        link: /usr/bin/python
        name: python
        priority: 1

    - name: Build hosts file
      ansible.builtin.lineinfile: 
        path: /etc/hosts 
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_eth1.ipv4.address }} {{ item }}"
        state: present
        mode: 0644
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      loop: "{{ groups[repmgr_target_group] }}"

    - name: Install acl package
      ansible.builtin.apt: 
        name: acl
