---
- name: Prepare
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Install python dependencies
      apt: 
        name: python3-apt
        update_cache: yes

    - name: Ensure python is available in PATH
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3
        priority: 1
