---
- name: Prepare
  hosts: pgcluster
  gather_facts: no
  become: yes

  pre_tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:

    - name: Run apt update via shell # Until https://github.com/ansible/ansible/issues/28991
      ansible.builtin.shell: rm -vrf /var/lib/apt/lists/* && apt-get clean && apt-get update
      become: yes

    - name: Gather facts for the first time
      ansible.builtin.setup:

    - name: Install python dependencies
      ansible.builtin.apt: 
        name: 
          - python3-apt
        update_cache: yes

    - name: Use python3 by default
      community.general.alternatives: 
        path: /usr/bin/python3
        link: /usr/bin/python
        name: python
        priority: 1

    - name: Build hosts file
      ansible.builtin.lineinfile: 
        path: /etc/hosts 
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{ item }}"
        state: present
        mode: 0644
      when: hostvars[item].ansible_host is defined
      loop: "{{ groups[repmgr_target_group] }}"

    - name: Install acl package
      ansible.builtin.apt:
        name: acl

    - name: Install barman-cli package
      ansible.builtin.apt:
        name: barman-cli
